<template>
    <div>
        <div>switch组件</div>
        <div>switch组件</div>
        <div>switch组件</div>
        <div>switch组件</div>
        <div>switch组件</div>
        <div>switch组件</div>
        <div>switch组件</div>
        <div>switch组件</div>
        <div>switch组件</div>
        <div>switch组件</div>
        <div>switch组件</div>
        <div>switch组件</div>
        <div>switch组件</div>
        <div>switch组件</div>
        <div>switch组件</div>
        <div>switch组件</div>
        <div>switch组件</div>
        <div>switch组件</div>
        <div>switch组件</div>
        <div>switch组件</div>
        <div>switch组件</div>
        <div>switch组件</div>
        <div>switch组件</div>
        <div>switch组件</div>
        <div>switch组件</div>
        <div>switch组件</div>
        <div>switch组件</div>
        <div>switch组件</div>
        <div>switch组件</div>
        <div>switch组件</div>
        <div>switch组件</div>
        <div>switch组件</div>
        <div>switch组件</div>
        <div>switch组件</div>
        <div>switch组件</div>
        <div>switch组件</div>
        <div>switch组件</div>
        <div>switch组件</div>
    </div>
</template>